name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar pruebas (si tienes pruebas en tu proyecto)
      - name: Run tests
        run: |
          pytest

      # Paso 5: Configurar la identidad de Git para hacer commit
      - name: Set Git identity for commit
        run: |
          git config --global user.name "David Rengifo"
          git config --global user.email "david.rengifo88@gmail.com"

      # Paso 6: Incrementar la versión usando bumpversion
      - name: Increment version and update changelog
        run: |
          bumpversion patch --allow-dirty
          git add VERSION .bumpversion.cfg
          git commit -m "Bump version"
          git push origin main

      # Paso 7: Desplegar a LocalStack o a la nube
      - name: Deploy to LocalStack or Cloud
        run: |
          echo "Deploying to LocalStack or Cloud"
