name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar pruebas (si tienes pruebas en tu proyecto)
      - name: Run tests
        run: |
          pytest

      # Paso 5: Configurar la identidad de Git para hacer commit
      - name: Set Git identity for commit
        run: |
          git config --global user.name "David Rengifo"
          git config --global user.email "david.rengifo88@gmail.com"

      # Paso 6: Incrementar la versión usando bumpversion
      - name: Increment version and update changelog
        run: |
          echo "Contenido de VERSION antes de bumpversion"
          cat VERSION  # Verifica el contenido de VERSION

          # Forzar la actualización de la versión
          bumpversion patch --allow-dirty

          echo "Contenido de VERSION después de bumpversion"
          cat VERSION  # Verifica si el archivo VERSION se actualizó

          # Verifica el estado de Git
          git status

          # Si hay cambios, hacer commit
          git add VERSION .bumpversion.cfg

          # Realiza el commit de los cambios
          git commit -m "Bump version"

          # Asegúrate de que el token sea accesible y lo uses para el push
          echo "Verificando si el token está disponible"
          echo "GIT_TOKEN=${{ secrets.GIT_TOKEN }}"  # Verifica si el token está accesible

          # Establece el repositorio remoto con el token para hacer push
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/DalexR8824/lintik_prueba.git

          # Empuja los cambios a GitHub
          git push origin main

      # Paso 7: Desplegar a LocalStack o a la nube
      - name: Deploy to LocalStack or Cloud
        run: |
          echo "Deploying to LocalStack or Cloud"
